import { CollectionConfig } from 'payload';

export const Events: CollectionConfig = {
  slug: 'events',
  fields: [
    { name: 'name', type: 'text' },
    { name: 'type', type: 'text' },
    { name: 'description', type: 'textarea' },
    { name: 'start_date', type: 'date' },
    { name: 'end_date', type: 'date' },
    { name: 'banner', type: 'text' },
    { name: 'org_id', type: 'number' },
    { name: 'sub_org_id', type: 'number' },
    { name: 'featured', type: 'checkbox' },
    { name: 'unique_id', type: 'text' },
    { name: 'campus_exclusive', type: 'checkbox' },
    { name: 'location', type: 'textarea' },
    { name: 'map_url', type: 'text' },
    { name: 'status', type: 'text', defaultValue: 'draft' },
    { name: 'is_invite_only', type: 'checkbox' },
    { name: 'is_virtual', type: 'checkbox' },
    { name: 'is_limited_seats', type: 'checkbox' },
    { name: 'number_of_seats', type: 'number' },
    { name: 'seats_available', type: 'number' },
    { name: 'is_external', type: 'checkbox' },
    { name: 'is_space', type: 'checkbox' },
    { name: 'is_project_based', type: 'checkbox' },
    { name: 'meet_url', type: 'text' },
    { name: 'project_submission_deadline', type: 'date' },
    { name: 'allow_non_github_links', type: 'checkbox' },
    { name: 'is_team_project_submission', type: 'checkbox' },
    { name: 'external_event_url', type: 'text' },
    { name: 'interests', type: 'text' },
    { name: 'skills', type: 'json' },
    { name: 'pre_invite', type: 'checkbox' },
    { name: 'report_submitted', type: 'checkbox' },
    { name: 'team_event', type: 'checkbox' },
    { name: 'team_size', type: 'number' },
    { name: 'multiple_venue', type: 'checkbox' },
    { name: 'discord_channel_url', type: 'text' },
    { name: 'discord_channel_name', type: 'text' },
    { name: 'is_dependent', type: 'checkbox' },
    { name: 'has_prize', type: 'checkbox' },
    { name: 'registration_deadline', type: 'date' },
    { name: 'group_id', type: 'number' },
    { name: 'prize_claim_deadline', type: 'date' },
    { name: 'group_mandatory', type: 'checkbox' },
  ],
};

