import { CollectionConfig } from 'payload';

export const Memberships: CollectionConfig = {
  slug: 'memberships',
  fields: [
    { name: 'name', type: 'text' },
    { name: 'username', type: 'text' },
    { name: 'avatar', type: 'text' },
    { name: 'bio', type: 'textarea' },
    { name: 'github', type: 'text' },
    { name: 'instagram', type: 'text' },
    { name: 'linkedin', type: 'text' },
    { name: 'twitter', type: 'text' },
    { name: 'user_id', type: 'number' },
    { name: 'org_id', type: 'number' },
    { name: 'sub_org_id', type: 'number' },
    { name: 'role_id', type: 'number' },
    { name: 'unique_id', type: 'text' },
    { name: 'sex', type: 'text' },
    { name: 'interests', type: 'textarea' },
    { name: 'is_student', type: 'checkbox' },
    { name: 'is_approved', type: 'checkbox' },
    { name: 'company_name', type: 'text' },
    { name: 'job_type', type: 'text' },
    { name: 'invited_by', type: 'number' },
    { name: 'email', type: 'email' },
    { name: 'enable_communication', type: 'checkbox' },
    { name: 'birthday', type: 'date' },
    { name: 'course', type: 'text' },
    { name: 'stream', type: 'text' },
    { name: 'year_of_admission', type: 'number' },
    { name: 'year_of_graduation', type: 'number' },
    { name: 'skills', type: 'json' },
    { name: 'is_onboard', type: 'checkbox' },
    { name: 'discord_id', type: 'text' },
    { name: 'theme', type: 'text', defaultValue: 'mangosteen' },
    { name: 'github_token', type: 'text' },
    { name: 'username_id', type: 'number' },
    { name: 'is_private', type: 'checkbox' },
    { name: 'tshirt_size', type: 'text' },
    { name: 'checkin_report_submitted', type: 'checkbox' },
    { name: 'address', type: 'json' },
    { name: 'is_guest', type: 'checkbox' },
    { name: 'status', type: 'text', defaultValue: 'unknown' },
  ],
};


